# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faeaa958992523e5eeed4082d90d8dc5c5a10bef1e198c3d8cad912edabd22b5abdd90935f791102e4ba0ab7684e107964a8ab71e4d803e70740d53d21616b78

test:
  secret_key_base: 1962f273e27e2e2231798a56707bb9efac55973c34e5ac398cb5b4ef71c4188467ab81c9641d4b79be4366a524becfd35219b3e2fd11289b047b52d878ad18e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
